### ISSUE TITLE
Q_galore 

### ISSUE THREAD

**Issue by Khaledbouza** [modelscope/swift#1451]
i want use Q_galore to train 100 million parameter in single gpu i can’t find custom template the model

**Comment by tastelikefeet** [comment]
I cannot get you.
What do you mean by 'template'?
if you want to know the template of each model, you just need to specify model by --model_type xxx, the template will automatically be matched and used.
Please check the documentation: 
https://swift.readthedocs.io/en/latest/LLM/Supported-models-datasets.html

**Comment by Khaledbouza** [comment]
@tastelikefeet  yeah this what i mean a model type iam looking for small seize like gpt2 model with 120 million parameter all listed model are bigger but i guess my gpu could handle with qgalore training from scratch a model 100m , or if there is a way customization model parameter

**Comment by tastelikefeet** [comment]
This is hard...
Because all supported models are pretrained, this means you cannot customize model layers or hidden_sizes, else the checkpoint cannot be used...
I think a better way is to use a smaller model directly
If you insist to modify the model parameters, check this file:
https://huggingface.co/openai-community/gpt2/blob/main/config.json
Modify some configs in this file(every model's config.json) may work

**Comment by Khaledbouza** [comment]
thank you i will try
